apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  ADMIN_USERID: YWRtaW4=
  ADMIN_APITOKEN: dGVjaHVzZXIK
  TECHUSER_USERID: dGVjaHVzZXJ0ZXN0
  TECHUSER_APITOKEN: dGVjaHVzZXJ0ZXN0

---

apiVersion: v1
kind: Secret
metadata:
  name: psql-secret
type: Opaque
data:
  DATABASE_USERNAME: cGRzX211bHRp
  DATABASE_PASSWORD: cGRzX3Rlc3QxMjM=
